### PR TITLE
Add flags on title search results and individual titles

### PR DESCRIPTION
**Pull request by CarlGraff**
This replaces Language Badge Codes with associated flags for both the search results page and indivdual title pages. Function getFlag has additional paramter to select flag style. There is room to include the badge codes next to the flags if desired.

### CODE REVIEW

**Comment by CarlGraff** [comment]
Here is screenshot of flags added to search results:
image


Here is screenshot of flag on individual title:
image

**Comment by NickEngmann** [comment]
Hey Carl, I think those flag icons are far too large. Could you make them the same size as the Book/Periodical tags that appear in the left corner?

**Comment by CarlGraff** [comment]
Ok Reduced size of flags as shown here on search results:

image

And here on individual title page:
image

**Comment by NickEngmann** [comment]
Looking Great! Thanks for the quick adjustments!

bitmoji

**Pull request merged**
